%YAML 1.3
---
title: "T-Jump Analysis Configuration"
experiment: "{{ $EXPERIMENT }}"
#run: "{{ $RUN_NUM }}"
date: "2025/07/29"
lute_version: 0.1      # Do not be change unless need to force older version
task_timeout: 6000
work_dir: ""
...
---
TJump:
  # Path to your custom processing script
  executable: "/path/to/your/tjump_script.py"
  
  # Input from previous smalldata task (leave empty to auto-retrieve from SubmitSMD)
  input_h5: ""
  
  # Output directory for results, default to /sdf/data/lcls/ds/{hutch}/{exp}/stats/summary/TJump
  output_dir: ""
  
  # Output h5 file name, default to scaled_and_processed.h5
  output_h5: ""
... 