%YAML 1.3
---
title: "T-Jump Analysis Configuration"
experiment: "{{ $EXPERIMENT }}"
run: "{{ $RUN_NUM }}"
date: "2025/08/15"
lute_version: 0.1      # Do not be change unless need to force older version
task_timeout: 6000
work_dir: ""
...
---
TJump:
  # REQUIRED: Path to your custom processing script
  python_script: "/sdf/data/lcls/ds/mfx/{{ $EXPERIMENT }}/results/doris/tjump_LUTE/sd2qwp1.py"
  
  # [REQUIRED FOR NOW]: Input from previous smalldata task
  input_h5: "/sdf/data/lcls/ds/mfx/{{ $EXPERIMENT }}/hdf5/smalldata/{{ $EXPERIMENT }}_Run{{ $RUN_NUM:04d }}.h5"
  
  # OPTIONAL: Output directory for results, default to the following
  # output_dir: "/sdf/data/lcls/ds/mfx/{{ $EXPERIMENT }}/stats/summary/TJump/{{ $RUN_NUM:04d }}"
  
  # OPTIONAL: Output h5 file name, default to the following
  # output_h5: "run{{ $RUN_NUM:04d }}_sd2qwp1.hdf5"
... 
